name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Use Node.js version 20
        uses: actions/setup-node@v2
        with:
          node-version: '20' 
      - name: Install dependencies
        run: npm install

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }} 
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
