name: Build/release

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2 # Update to v2

      - name: Set up Node.js
        uses: actions/setup-node@v2 # Update to v2
        with:
          node-version: 14 # Change to the desired Node.js version

      - name: Install Yarn
        run: npm install -g yarn@latest # Install latest version of Yarn

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder # Update to v2
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }} # Update to GH_TOKEN

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
