name: Weekly Build

on:
  schedule:
    - cron: '0 0 * * 0'  # Schedule to run every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Increment version
        run: npm version minor --force

      - name: Build for Linux
        run: npm run build-linux

      - name: Build for Windows
        run: npm run build-win
